package com.example.ap2_covid_dashboard.api.covidreports.worldwide.enums

enum class CountryEnum(name: String) {
    AUSTRALIA("Australia"),
    AUSTRIA("Austria"),
    CANADA("Canada"),
    CHINA("China"),
    DENMARK("Denmark"),
    FINLAND("Finland"),
    FRANCE("France"),
    GERMANY("Germany"),
    ICELAND("Iceland"),
    IRELAND("Ireland"),
    ITALY("Italy"),
    NETHERLANDS("Netherlands"),
    NORWAY("Norway"),
    RUSSIA("Russia"),
    SWEDEN("Sweden"),
    SWITZERLAND("Switzerland"),
    UNITED_KINGDOM("United Kingdom"),
    US("US"),
    SPAIN("Spain"),
    AFGHANISTAN("Afghanistan"),
    ALBANIA("Albania"),
    ALGERIA("Algeria"),
    ANDORRA("Andorra"),
    ANGOLA("Angola"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda"),
    ARGENTINA("Argentina"),
    ARMENIA("Armenia"),
    AZERBAIJAN("Azerbaijan"),
    BAHAMAS("Bahamas"),
    BAHRAIN("Bahrain"),
    BANGLADESH("Bangladesh"),
    BARBADOS("Barbados"),
    BELARUS("Belarus"),
    BELGIUM("Belgium"),
    BELIZE("Belize"),
    BENIN("Benin"),
    BHUTAN("Bhutan"),
    BOLIVIA("Bolivia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina"),
    BOTSWANA("Botswana"),
    BRAZIL("Brazil"),
    BRUNEI("Brunei"),
    BULGARIA("Bulgaria"),
    BURKINA_FASO("Burkina Faso"),
    BURMA("Burma"),
    BURUNDI("Burundi"),
    CABO_VERDE("Cabo Verde"),
    CAMBODIA("Cambodia"),
    CAMEROON("Cameroon"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic"),
    CHAD("Chad"),
    CHILE("Chile"),
    COLOMBIA("Colombia"),
    COMOROS("Comoros"),
    CONGO("Congo (Brazzaville)"),
    COSTA_RICA("Costa Rica"),
    COTE_DIVOIRE("Cote d'Ivoire"),
    CROATIA("Croatia"),
    CUBA("Cuba"),
    CYPRUS("Cyprus"),
    CZECHIA("Czechia"),
    DIAMOND_PRINCESS("Diamond Princess"),
    DJIBOUTI("Djibouti"),
    DOMINICA("Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic"),
    ECUADOR("Ecuador"),
    EGYPT("Egypt"),
    EL_SALVADOR("El Salvador"),
    EQUATORIAL_GUINEA("Equatorial Guinea"),
    ERITREA("Eritrea"),
    ESTONIA("Estonia"),
    ESWATINI("Eswatini"),
    ETHIOPIA("Ethiopia"),
    FIJI("Fiji"),
    GABON("Gabon"),
    GAMBIA("Gambia"),
    GEORGIA("Georgia"),
    GHANA("Ghana"),
    GREECE("Greece"),
    GRENADA("Grenada"),
    GUATEMALA("Guatemala"),
    GUINEA("Guinea"),
    GUINEA_BISSAU("Guinea-Bissau"),
    GUYANA("Guyana"),
    HAITI("Haiti"),
    HOLY_SEE("Holy See"),
    HONDURAS("Honduras"),
    HUNGARY("Hungary"),
    INDIA("India"),
    INDONESIA("Indonesia"),
    IRAN("Iran"),
    IRAQ("Iraq"),
    ISRAEL("Israel"),
    JAMAICA("Jamaica"),
    JAPAN("Japan"),
    JORDAN("Jordan"),
    KAZAKHSTAN("Kazakhstan"),
    KENYA("Kenya"),
    KOREA_SOUTH("Korea, South"),
    KOSOVO("Kosovo"),
    KUWAIT("Kuwait"),
    KYRGYZSTAN("Kyrgyzstan"),
    LAOS("Laos"),
    LATVIA("Latvia"),
    LEBANON("Lebanon"),
    LESOTHO("Lesotho"),
    LIBERIA("Liberia"),
    LIBYA("Libya"),
    LIECHTENSTEIN("Liechtenstein"),
    LITHUANIA("Lithuania"),
    LUXEMBOURG("Luxembourg"),
    MS_ZAANDAM("MS Zaandam"),
    MADAGASCAR("Madagascar"),
    MALAWI("Malawi"),
    MALAYSIA("Malaysia"),
    MALDIVES("Maldives"),
    MALI("Mali"),
    MALTA("Malta"),
    MAURITANIA("Mauritania"),
    MAURITIUS("Mauritius"),
    MEXICO("Mexico"),
    MOLDOVA("Moldova"),
    MONACO("Monaco"),
    MONGOLIA("Mongolia"),
    MONTENEGRO("Montenegro"),
    MOROCCO("Morocco"),
    MOZAMBIQUE("Mozambique"),
    NAMIBIA("Namibia"),
    NEPAL("Nepal"),
    NEW_ZEALAND("New Zealand"),
    NICARAGUA("Nicaragua"),
    NIGER("Niger"),
    NIGERIA("Nigeria"),
    NORTH_MACEDONIA("North Macedonia"),
    OMAN("Oman"),
    PAKISTAN("Pakistan"),
    PANAMA("Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea"),
    PARAGUAY("Paraguay"),
    PERU("Peru"),
    PHILIPPINES("Philippines"),
    POLAND("Poland"),
    PORTUGAL("Portugal"),
    QATAR("Qatar"),
    ROMANIA("Romania"),
    RWANDA("Rwanda"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis"),
    SAINT_LUCIA("Saint Lucia"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines"),
    SAN_MARINO("San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe"),
    SAUDI_ARABIA("Saudi Arabia"),
    SENEGAL("Senegal"),
    SERBIA("Serbia"),
    SEYCHELLES("Seychelles"),
    SIERRA_LEONE("Sierra Leone"),
    SINGAPORE("Singapore"),
    SLOVAKIA("Slovakia"),
    SLOVENIA("Slovenia"),
    SOMALIA("Somalia"),
    SOUTH_AFRICA("South Africa"),
    SOUTH_SUDAN("South Sudan"),
    SRI_LANKA("Sri Lanka"),
    SUDAN("Sudan"),
    SURINAME("Suriname"),
    SYRIA("Syria"),
    TAIWAN("Taiwan*"),
    TAJIKISTAN("Tajikistan"),
    TANZANIA("Tanzania"),
    THAILAND("Thailand"),
    TIMOR_LESTE("Timor-Leste"),
    TOGO("Togo"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago"),
    TUNISIA("Tunisia"),
    TURKEY("Turkey"),
    UGANDA("Uganda"),
    UKRAINE("Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates"),
    URUGUAY("Uruguay"),
    UZBEKISTAN("Uzbekistan"),
    VENEZUELA("Venezuela"),
    VIETNAM("Vietnam"),
    WEST_BANK_AND_GAZA("West Bank and Gaza"),
    WESTERN_SAHARA("Western Sahara"),
    YEMEN("Yemen"),
    ZAMBIA("Zambia"),
    ZIMBABWE("Zimbabwe")
}